### ISSUE TITLE
exclude-patterns and include-patterns Not Working in DeepSeek Code Review Action

### ISSUE THREAD

**Issue by bbz1024** [hustcer/deepseek-review#120]
## 问题描述

在`deepseek-cr.yaml`文件中尝试使用`exclude-patterns`和`include-patterns`参数以控制[具体动作或步骤]的行为时，发现这两个参数并未按预期工作，且我只需要cr某个文件夹。

## 配置示例

以下是相关配置片段：
```
name: Code Review
on:
  pull_request:
    branches: [main,testcr]

permissions:
  pull-requests: write

jobs:
  code-review:
    runs-on: ubuntu-latest
    name: Code Review
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: DeepSeek Code Review
        uses: hustcer/deepseek-review@v1
        with:
          chat-token: ${{ secrets.DEEPSEEK_CHAT_TOKEN }} # DeepSeek API Token
          model: deepseek-chat
          sys-prompt: "请专注于检查 Go 文件中的代码质量问题，包括但不限于代码风格、逻辑错误和安全漏洞，并提出具体的改进建议。"
          user-prompt: "请审查以下 Go 文件的代码变更"
#          include-patterns: "*.sql"
          exclude-patterns: "*.sql"
```

## 请求帮助

请问是否有关于`include-patterns`和`exclude-patterns`使用的特殊要求或限制？是否有其他配置项需要同时调整才能使这两个参数生效？

感谢您的支持

**Comment by hustcer** [comment]
你可以先在本地 review 远程的 PR 然后加上 -d 参数查看 diff 内容是否生效，这两个 pattern 是通过 awk 过滤的，本地调试没问题再到 wf 里面使用
你也可以留下仓库和 PR 编号，我晚点本地排查下

**Comment by bbz1024** [comment]
## 问题描述
我是想只进行cr项目下`**/internal/**`所有文件

- 我的配置
```
name: Code Review
on:
  pull_request:
    branches: [main,testcr]

permissions:
  pull-requests: write

jobs:
  code-review:
    runs-on: ubuntu-latest
    name: Code Review
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: DeepSeek Code Review
        uses: hustcer/deepseek-review@v1
        with:
          chat-token: ${{ secrets.DEEPSEEK_CHAT_TOKEN }} # DeepSeek API Token
          model: deepseek-chat
          sys-prompt: "请专注于检查 Go 文件中的代码质量问题，包括但不限于代码风格、逻辑错误和安全漏洞，并提出具体的改进建议。"
          user-prompt: "请审查以下 Go 文件的代码变更"
          include-patterns: "**/internal/**" # 由awk过滤
```
- 失败日志
![Image](https://github.com/user-attachments/assets/38be78e0-e279-4da6-8667-19008207433e)

## 仓库地址
https://github.com/bbz1024/min-tiktok/tree/testcr2/.github/workflows

## 最后
感谢您的回复，我会继续支持该项目的。
