### ISSUE TITLE
github 新增了flow action, 更新了文档，但是无法正常review代码

### ISSUE THREAD

**Issue by zhenghongri** [hustcer/deepseek-review#153]
github 新增了flow action, 更新了文档，但是无法正常review代码，是配置的问题嘛？

``` yaml
name: learn-github-actions-deepseek
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: DeepSeek Code Review
        uses: hustcer/deepseek-review@v1.12
        with:
          chat-token: sk-912721c3ef0540e7a7615e430c33e709
```

![Image](https://github.com/user-attachments/assets/bdc5e906-1b27-42f5-b5b8-5f03dcea26a8)

![Image](https://github.com/user-attachments/assets/9180bb28-c68e-4474-9a63-6c11be647b8e)

**Comment by hustcer** [comment]
这个是你的 workflow 配置问题啊，参考下 README：
```yaml
name: Code Review
on:
  pull_request_target:
    types:
      - opened      # Triggers when a PR is opened
      - reopened    # Triggers when a PR is reopened
      - synchronize # Triggers when a commit is pushed to the PR

# fix: GraphQL: Resource not accessible by integration (addComment) error
permissions:
  pull-requests: write

jobs:
  setup-deepseek-review:
    runs-on: ubuntu-latest
    name: Code Review
    steps:
      - name: DeepSeek Code Review
        uses: hustcer/deepseek-review@v1
        with:
          chat-token: ${{ secrets.CHAT_TOKEN }}
```

另外 你的 CHAT_TOKEN 不要明文存储，泄露了
